var toArray = require('@timelaps/to/array'),
    concatUnique = require('@timelaps/array/concat/unique'),
    Events = toArray('abort,afterprint,beforeprint,blocked,cached,canplay,canplaythrough,change,chargingchange,chargingtimechange,checking,close,complete,dischargingtimechange,DOMContentLoaded,downloading,durationchange,emptied,ended,error,fullscreenchange,fullscreenerror,input,invalid,languagechange,levelchange,loadeddata,loadedmetadata,message,noupdate,obsolete,offline,online,open,pagehide,pageshow,paste,pause,pointerlockchange,pointerlockerror,play,playing,ratechange,reset,seeked,seeking,stalled,storage,submit,success,suspend,timeupdate,updateready,upgradeneeded,versionchange,visibilitychange'),
    SVGEvent = toArray('SVGAbort,SVGError,SVGLoad,SVGResize,SVGScroll,SVGUnload,SVGZoom,volumechange,waiting'),
    KeyboardEvent = toArray('keydown,keypress,keyup'),
    GamePadEvent = toArray('gamepadconnected,gamepadisconnected'),
    CompositionEvents = toArray('compositionend,compositionstart,compositionupdate,drag,dragend,dragenter,dragleave,dragover,dragstart,drop'),
    MouseEvents = toArray('click,contextmenu,dblclick,mousedown,mouseenter,mouseleave,mousemove,mouseout,mouseover,mouseup,show,wheel'),
    TouchEvents = toArray('touchcancel,touchend,touchenter,touchleave,touchmove,touchstart'),
    DeviceEvents = toArray('devicemotion,deviceorientation,deviceproximity,devicelight'),
    FocusEvents = toArray('blur,focus'),
    TimeEvents = toArray('beginEvent,endEvent,repeatEvent'),
    AnimationEvents = toArray('animationend,animationiteration,animationstart,transitionend'),
    AudioProcessingEvents = toArray('audioprocess,complete'),
    UIEvents = toArray('abort,error,hashchange,load,orientationchange,readystatechange,resize,scroll,select,unload,beforeunload'),
    ProgressEvent = toArray('abort,error,load,loadend,loadstart,popstate,progress,timeout'),
    AllEvents = concatUnique([Events, SVGEvent, KeyboardEvent, CompositionEvents, GamePadEvent, MouseEvents, TouchEvents, DeviceEvents, FocusEvents, TimeEvents, AnimationEvents, AudioProcessingEvents, UIEvents, ProgressEvent]);
module.exports = {
    base: Events,
    svg: SVGEvent,
    keyboard: KeyboardEvent,
    gamepad: GamePadEvent,
    composition: CompositionEvents,
    mouse: MouseEvents,
    touch: TouchEvents,
    device: DeviceEvents,
    focus: FocusEvents,
    time: TimeEvents,
    animation: AnimationEvents,
    audioProcessing: AudioProcessingEvents,
    ui: UIEvents,
    progress: ProgressEvent,
    all: AllEvents
};